[package]
name = "rust_mailer"
version = "0.1.0"
edition = "2021"

[workspace]
members = [".", "./services/mailer/"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.3.1"
dotenvy = "0.15.7"
mailer = {path = "services/mailer"}
serde = { version = "0.12", features = ["derive"] }
tokio = "1.32.0"
