services:
    mailer:
        container_name: mailer
        build: .
        restart: always
        ports:
            - 4000:4000
        volumes:
          - .:/app
        env_file:
            - .env
volumes:
    mailer: