services:
    mailer:
        container_name: mailer
        build:
            context: .
            # dockerfile: Dockerfile # uncomment this line for production
            dockerfile: Dockerfile.dev
        restart: always
        ports:
            - 4000:4000
        volumes:
          - .:/usr/src/app
        env_file:
            - .env
volumes:
    mailer: