services:
    mailer:
        container_name: mailer
        build:
            context: .
            dockerfile: dev.dockerfile
            #dockerfile: prod.dockerfile # uncomment this line for production build
        restart: always
        ports:
            - 4000:4000
        volumes:
          - .:/usr/src/app
        env_file:
            - .env