FROM node:latest AS node_base

FROM rust:latest
COPY --from=node_base / /
WORKDIR /usr/src/app

COPY . .

# RUN cargo install --path .
# RUN npx nodemon --watch src -e rs --exec cargo run

CMD [ "npx", "nodemon", "--watch", "src", "-e", "rs", "--exec", "cargo run" ] 